---
- name: Create spot request
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    instance_type: m3.medium
    security_group: MY_SECURITY_GROUP # Change the security group name here
    image: ami-a9d276c9 # Change the AMI, from which you want to launch the server
    region: us-west-2 # Change the Region
    zone: us-west-2a
    keypair: MYKEYPAIR # Change the keypair name
    spot_type:  one-time
    spot_price: 0.019
    count: 1

  tasks:
    - name: Set new spot requests
      ec2:
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        region: "{{region}}"
        keypair: "{{keypair}}"
        count: "{{count}}"
        group: "{{security_group}}"
        spot_price: "{{spot_price}}"
        spot_type:  "{{spot_type}}"
        zone: "{{ zone }}"
        spot_wait_timeout: 60
        wait: yes
        user_data: |
          #!/bin/bash
          {{ lookup('file', 'user_data') }}
      register: ec2

    - name: Add tag to Instance(s)
      ec2_tag:
        resource: "{{item.id}}"
        region: "{{region}}"
        state: present
      with_items: "{{ec2.instances}}"
      args:
        tags:
          Name: deployed-by-ansible
